main: cc.ajneb97.ChristmasCalendar
version: 2.0.2.3
name: JrChristmasCalendar
authors: [Ajneb97, JoaquingameR1717]
api-version: 1.13
depend: [NBTAPI]
commands:
  calendar:
    description: Christmas Calendar main command
